### Create article
POST localhost:8080/api/v1/article
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI5OTI0ODUsImlkIjo0LCJyb2xlIjoiTU9ERVJBVE9SIiwiZXhwIjoxNjgzMDc4ODg1LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.TKMFHR6doV4-opnfNz1RB53Vpp-v9kwqdLepGVW9avzXLGK15ErUBCRgrjvTHo4H81yhoB1nZQbsKHy4O5QcFw

{
  "title": "fdssafdsf",
  "description": "asdfdsfdsdfs",
  "content": "sdfsdfdsfsadfsdf",
  "attachId": 1,
  "regionId": 2,
  "categoryId": 3,
  "articleTypeId": 1
}