### create article
POST localhost:8080/api/v1/article/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NTA2MDAsImlkIjoxMywicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4MjgzNzAwMCwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.c7OMEp_IJrAh5MHHrbEyc4gpGXdLHBB2TuinPufgRg_ZFNWDvfCJb7r232FleHg_RerdJNGO-r3FRn0tE0d9pA
Content-Type: application/json

{
  "title": "Sdfvdfvcxsdfvddfgfsvvcdsf ",
  "description": "dfvbsm, ;ljg bflkmx dlk;mgvc ",
  "content": "dfgl,ml;df;ld;fldfdl,;fldsfdfl;fg;lf;l,gfgl;dfmjklnjk ;fdgc ",
  "categoryId": 1,
  "regionId": 2,
  "typeId": 3
}

### update article

POST localhost:8080/api/v1/article/update/6619a2aa-2198-416c-818d-7b66b5211b31
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NTA2MDAsImlkIjoxMywicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4MjgzNzAwMCwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.c7OMEp_IJrAh5MHHrbEyc4gpGXdLHBB2TuinPufgRg_ZFNWDvfCJb7r232FleHg_RerdJNGO-r3FRn0tE0d9pA
Content-Type: application/json

{
  "title": "efvdsm, ewlkvds ,.",
  "description": "elfm krkoelmdslc,.xcm",
  "content": "wrkjvefmefmfdkdkdkdk",
  "categoryId": 2,
  "regionId": 1,
  "typeId": 1,
  "imageId": 3,
  "visible": true
}

### delete article update visible to false
DELETE localhost:8080/api/v1/article/delete/bc78aaa6-ab91-440c-9972-49c4f2887ef0
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NTA2MDAsImlkIjoxMywicm9sZSI6Ik1PREVSQVRPUiIsImV4cCI6MTY4MjgzNzAwMCwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.c7OMEp_IJrAh5MHHrbEyc4gpGXdLHBB2TuinPufgRg_ZFNWDvfCJb7r232FleHg_RerdJNGO-r3FRn0tE0d9pA

###Change status by id (PUBLISHER) (publish,not_publish)
PUT localhost:8080/api/v1/article/publish/dc9c0983-7e3e-4144-b950-6b051ab2ac8f?status = PUBLISHED
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NTIwNjIsImlkIjoxNCwicm9sZSI6IlBVQkxJU0hFUiIsImV4cCI6MTY4MjgzODQ2MiwiaXNzIjoiS3VudXogdGVzdCBwb3J0YWxpIn0.bloIUJRZbWDtc9bgp4YaP9R6lvju4zBrHLl9QkfnV98027bHw7q-mTARKO2ylJdoTsUhYhvw5DZd8r3kNPczGQ

###  Get Last 5 Article By Types  ordered_by_created_date
GET localhost:8080/api/v1/article/publish/5/2
### Get Last 3 Article By Types  ordered_by_created_date
GET localhost:8080/api/v1/article/publish/3/2
### get top 8
GET localhost:8080/api/v1/article/publish/8/2
### Get Article By Id And Lang
GET localhost:8080/api/v1/article/publish?id=dc9c0983-7e3e-4144-b950-6b051ab2ac8f&lang=en

###  Get Last 4 Article By Types and except given article id.
GET localhost:8080/api/v1/article/publish/4?articleId=dc9c0983-7e3e-4144-b950-6b051ab2ac8f&typeId=2
### Get 4 most read articles
GET localhost:8080/api/v1/article/publish/top/4


###Get Last 5 Article By Types  And By Region Key
GET localhost:8080/api/v1/article/publish/region/5?regionId=1&typeId=2


###Get Article list by Region Key (Pagination)
GET localhost:8080/api/v1/article/publish/region?regionId=1&page=2&size=2

### Get Last 5 Article Category Key
GET localhost:8080/api/v1/article/publish/category/5/2

### Get Article By Category Key (Pagination)
GET localhost:8080/api/v1/article/publish/category?categoryId=2&size=2

