### Attach save photo
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test_imge_1.jpg"

< /Users/macuser/Downloads/test_imge_1.jpg

###  Attach get photo by name
GET http://localhost:8080/api/v1/attach/open/5aceb7fb-1790-4b20-878d-eb5a669c0895.jpg

### video
POST http://localhost:8080/api/v1/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="333.mp4"

< /Users/macuser/Downloads/33333.mp4

#< C:\Users\BigMan\Desktop\11\test_imge_1.jpg

###  Attach get video by name
GET http://localhost:8080/api/v1/attach/open_general/5aceb7fb-1790-4b20-878d-eb5a669c0895.jpg

###
GET http://localhost:8080/api/v1/attach/list-paging

### attach download
GET http://localhost:8080/api/v1/attach/download/test_imge_1.jpg


### attach delete
DELETE http://localhost:8080/api/v1/attach/deleteById/b67fcd30-d05a-473a-b748-cbb826ac6154
