### Create profile
POST localhost:8080/api/v1/profile/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI5OTA3NjksImlkIjo0LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODMwNzcxNjksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.P7jvhtUwqLy8PAd1xQFpZg18UfWCAky4tV6ZoPoAA6kljHs4ywuMrkl-yKbFrt-r3FgBFGo1fcJRxyE-VHg8_A
Content-Type:  application/json

{
  "name": "dgfchvjb",
  "surname": "gvhbjj",
  "email": "hcgvjbkn@mail.ru",
  "phone": "23456",
  "password": "09876",
  "role": "USER"
}

### Profile List with pagination
GET http://localhost:8080/api/v1/profile/list-paging

### Profile get by id
GET http://localhost:8080/api/v1/profile/4

### Profile delete by id
DELETE http://localhost:8080/api/v1/profile/5

### Profile update by Id with Admin
PUT http://localhost:8080/api/v1/profile/5
Content-Type: application/json

{
  "name": "sfvfg"
}

### Profile update by Id
PUT http://localhost:8080/api/v1/profile/5
Content-Type: application/json

{
  "name": "sfvfg"
}

###
PUT http://localhost:8080/api/v1/profile/update/5
Content-Type: application/json

{
  "name": "Toshmat",
  "surname": "Toshmatov",
  "phone": 12345,
  "password": "653"
}
