### Region create
POST http://localhost:8080/api/v1/region/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5MDc2MzgsImlkIjo0LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODE5OTQwMzgsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.fzwOPAPwBOqtT1y-Rd1lHwleqJ78LU25qdP5MwoUq2zEP7bQiLhOudqW2LBIPwO7DhumaA44_Yf0T5VbSHXKnA
Content-Type: application/json

{
  "nameUz": "Fargona",
  "nameRU": "Enisey",
  "nameEng": "Oxvord"
}

### Region update with id
PUT http://localhost:8080/api/v1/region/1
Content-Type: application/json

{
  "nameUz": "Andijon",
  "nameRU": "Russia",
  "nameEng": "England"
}

###  Region delete with id
DELETE http://localhost:8080/api/v1/region/3

### Regionx get all
GET http://localhost:8080/api/v1/region/list-paging

### Get by lang